# Generated by Django 3.2.7 on 2021-09-15 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210911_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2021, 9, 15), help_text='Введите дату рождения'),
        ),
    ]
